### ISSUE TITLE
Disambiguate between stops with equal names by showing the departures below the stop name

### ISSUE THREAD

**Issue by laurilehmijoki** [suominentoni/nearest-departures#1]
Hello Toni and thanks for Lähimmät Lähdöt!

Today while standing on a bus stop, I noticed that Lähimmät Lähdöt showed the stop on the opposite site of street as the nearest stop. In reality, I was standing on the nearest stop. Probably the GPS fix was a bit inaccurate, which resulted in Lähimmät Lähdöt showing me the wrong stop on top of the nearest stops list.

What could we do to prevent issues like this? Below is a screenshot of a solution that I came up with. There, we are listing the departures below the stop name. If the user is familiar with the destinations of the departures, he or she can disambiguate between stops with equal names.

What do you think about this idea?

![simulator screen shot 23 dec 2016 20 27 43](https://cloud.githubusercontent.com/assets/864166/21460201/501c7410-c94e-11e6-8a86-3a91b00bbd30.png)

The implementation I used to take the screenshot can be found [here](https://github.com/laurilehmijoki/nearest-departures/commits/show-departures-below-stops-in-nearest-departures).

Have a nice Xmas!

**Comment by suominentoni** [comment]
Hey Lauri!

I think it's an excellent idea! Jut submit a pull request and I'll include it in the next release. It's actually been a while since the previous release, and therefore I could do a release a.s.a.p. as this is merged.

**Comment by suominentoni** [comment]
And apologies for the late reply. I'd forgotten to watch this repo myself, so I did not get any notification about your issue.

**Comment by laurilehmijoki** [comment]
Okay I'll send you a PR in a few days! 

I think it would be a good idea to sort the departures by the delta to current moment and then remove duplicate entries from the list. In the screenshot this idea is not yet implemented. Let me know if you spot problems in this approach.

**Comment by suominentoni** [comment]
Yeah, sorting by time is definitely a good idea.

I kind of like the idea of having duplicates in the list, as it indicates that the next N departures will go to the same location. Compare:

`Arabia, Arabia, Arabia, Kannelmäki...`
`Arabia, Kannelmäki...`

What do you think?

**Comment by suominentoni** [comment]
On the other hand, listing the same name multiple times might leave some destinations hidden. In that sense removing duplicates is better. Maybe we should go with that option anyway.

Looking forward to hearing your opinion!

**Comment by laurilehmijoki** [comment]
I'd go without duplicates, because then the user can see an *overview* (all the unique destinations of a stop) first and then decide whether he or she is interested in *details* (how many of the next departures go into a particular destination).

I admit that someone can benefit from a UI where the duplicates are not removed.

**Comment by laurilehmijoki** [comment]
Accidentally closed the issue. Fumbling around with my phone :)

**Comment by suominentoni** [comment]
No worries :)

I agree with you on no duplicates being a better option.

**Comment by suominentoni** [comment]
Resolved in [PR #2](https://github.com/suominentoni/nearest-departures/pull/2).
