### ISSUE TITLE
Duplicated stops with one showing only busses and the other trams

### ISSUE THREAD

**Issue by vvilhonen** [suominentoni/nearest-departures#4]
![image](https://user-images.githubusercontent.com/88401/29918679-f2837e4a-8e4e-11e7-8f56-c17777092071.png)
![image](https://user-images.githubusercontent.com/88401/29918683-f638ad94-8e4e-11e7-8e56-023f4e67d9b5.png)
![image](https://user-images.githubusercontent.com/88401/29918684-f8205a4e-8e4e-11e7-9634-c5b9dae6c819.png)

**Comment by suominentoni** [comment]
Apparently the transit operator (HSL in this case) perceives this stop as two separate stops (one for busses as and the other for trams) even though it is physically just one stop.

In cases like these we could merge these two stops into one. Feel free to submit a Pull Request, if you feel like it.

Thanks for pointing this out!
